### ISSUE TITLE
Step 2 does not contain SwSandboxComponent

### ISSUE THREAD

**Issue by jziggas** [webmaxru/pwa-workshop-angular#4]

**Comment by tlahav** [comment]
Also stuck here. I see the file was removed from repo so i think ill just add it back locally for now.

**Comment by fauzyahmad** [comment]
can someone add SwSandboxComponent or how to create that? thanks

**Comment by webmaxru** [comment]
There is a new version of Angular PWA workshop released:
- Repo: https://github.com/webmaxru/angular-pwa
- Guidance document: https://bit.ly/ngsw-workshop

This repo will no longer be maintained.
