### ISSUE TITLE
No issue, when we start with " ng new app1 --service worker " in angular cli.

### ISSUE THREAD

**Issue by Sangeethaself** [webmaxru/pwa-workshop-angular#6]
No issue,  when we start with " **ng new app1 --service worker** "  in angular cli. 

I got run my sample app in service worker. thanks webmaxru for your documents.

**Comment by webmaxru** [comment]
There is a new version of Angular PWA workshop released:
- Repo: https://github.com/webmaxru/angular-pwa
- Guidance document: https://bit.ly/ngsw-workshop

This repo will no longer be maintained.
